apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  namespace: default
  name: spring-sensors
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: spring-sensors
    app.tanzu.vmware.com/deliverable-type: web
spec:
  serviceAccountName: default
  source:
    git:
      ref:
        branch: main
      url: https://github.com/akinsanyaleke/ops-spring-sensors
